// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOFOI3FHtrJdnDewyiZ0fmPdNRsRsr2V8',
    appId: '1:299498538786:web:5d9a0fc5e4f714fa9e477b',
    messagingSenderId: '299498538786',
    projectId: 'iheb-shop',
    authDomain: 'iheb-shop.firebaseapp.com',
    storageBucket: 'iheb-shop.appspot.com',
    measurementId: 'G-3YJTPZP9NS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8L_tUvmnkC8H-lJ8CUsleAP3jv_sy4O8',
    appId: '1:299498538786:android:eecd05fc4043e7249e477b',
    messagingSenderId: '299498538786',
    projectId: 'iheb-shop',
    storageBucket: 'iheb-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCex63H7-FgBCjQQ8V2xjmBwLkvxoZIuiU',
    appId: '1:299498538786:ios:b2a0c05aaffdf9559e477b',
    messagingSenderId: '299498538786',
    projectId: 'iheb-shop',
    storageBucket: 'iheb-shop.appspot.com',
    androidClientId: '299498538786-6ckhm58kiqqft8oudtq1p811tps5jnup.apps.googleusercontent.com',
    iosClientId: '299498538786-3gfmckrus4klnhe4hb9vitn0505lokhc.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceapp',
  );
}
